INSERT INTO usuarios (usuario,password,nombre,rol,email) VALUES
('departamentoartesplasticas','departamentoartesplasticas','Artes Plásticas','jefe/a departamento','departamentoartesplasticas@iesjuanbosco.es'),
('departamentocienciasnaturales','departamentocienciasnaturales','Ciencias Naturales','jefe/a departamento','departamentocienciasnaturales@iesjuanbosco.es'),
('departamentoeconomia','departamentoeconomia','Economía','jefe/a departamento','departamentoeconomia@iesjuanbosco.es'),
('departamentoeducacionfisicadeportiva','departamentoeducacionfisicadeportiva','Educación Física y Deportiva','jefe/a departamento','departamentoeducacionfisicadeportiva@iesjuanbosco.es'),
('departamentofilosofia','departamentofilosofia','Filosofía','jefe/a departamento','departamentofilosofia@iesjuanbosco.es'),
('departamentofisicaquimica','departamentofisicaquimica','Física y Química','jefe/a departamento','departamentofisicaquimica@iesjuanbosco.es'),
('departamentofol','departamentofol','Formación y Orientación Laboral','jefe/a departamento','departamentofol@iesjuanbosco.es'),
('departamentofrances','departamentofrances','Francés','jefe/a departamento','departamentofrances@iesjuanbosco.es'),
('departamentogeografiahistoria','departamentogeografiahistoria','Geografía e Historia','jefe/a departamento','departamentogeografiahistoria@iesjuanbosco.es'),
('departamentoingles','departamentoingles','Inglés','jefe/a departamento','departamentoingles@iesjuanbosco.es'),
('departamentolatingriego','departamentolatingriego','Latín y Griego','jefe/a departamento','departamentolatingriego@iesjuanbosco.es'),
('departamentolenguacastellana','departamentolenguacastellana','Lengua Castellana y Literatura','jefe/a departamento','departamentolenguacastellana@iesjuanbosco.es'),
('departamentomatematicas','departamentomatematicas','Matemáticas','jefe/a departamento','departamentomatematicas@iesjuanbosco.es'),
('departamentomusica','departamentomusica','Música','jefe/a departamento','departamentomusica@iesjuanbosco.es'),
('departamentotecnologia','departamentotecnologia','Tecnología','jefe/a departamento','departamentotecnologia@iesjuanbosco.es'),
('departamentosanidad','departamentosanidad','Sanidad','jefe/a departamento','departamentosanidad@iesjuanbosco.es'),
('departamentoactividadesfisicas','departamentoactividadesfisicas','Actividades Físicas y Deportivas','jefe/a departamento','departamentoactividadesfisicas@iesjuanbosco.es'),
('departamentoadministracion','departamentoadministracion','Administración','jefe/a departamento','departamentoadministracion@iesjuanbosco.es'),
('departamentocomercio','departamentocomercio','Comercio','jefe/a departamento','departamentocomercio@iesjuanbosco.es'),
('departamentoedificacionobracivil','departamentoedificacionobracivil','Edificación y Obra Civil','jefe/a departamento','departamentoedificacionobracivil@iesjuanbosco.es'),
('departamentoelectricidadelectronica','departamentoelectricidadelectronica','Electricidad y Electrónica','jefe/a departamento','departamentoelectricidadelectronica@iesjuanbosco.es'),
('departamentofabricacionmecanica','departamentofabricacionmecanica','Fabricación Mecánica','jefe/a departamento','departamentofabricacionmecanica@iesjuanbosco.es'),
('departamentoimagenpersonal','departamentoimagenpersonal','Imagen Personal','jefe/a departamento','departamentoimagenpersonal@iesjuanbosco.es'),
('departamentoinformatica','departamentoinformatica','Informática','jefe/a departamento','departamentoinformatica@iesjuanbosco.es');
