INSERT INTO usuarios (usuario,password,nombre,rol,email) VALUES
('profe1artesplasticas','profe1artesplasticas','Profesor/a Artes Plásticas','profesor','profe1artesplasticas@iesjuanbosco.es'),
('profe1cienciasnaturales','profe1cienciasnaturales','Profesor/a Ciencias Naturales','profesor','profe1cienciasnaturales@iesjuanbosco.es'),
('profe1economia','profe1economia','Profesor/a Economía','profesor','profe1economia@iesjuanbosco.es'),
('profe1educacionfisicadeportiva','profe1educacionfisicadeportiva','Profesor/a Educación Física y Deportiva','profesor','profe1educacionfisicadeportiva@iesjuanbosco.es'),
('profe1filosofia','profe1filosofia','Profesor/a Filosofía','profesor','profe1filosofia@iesjuanbosco.es'),
('profe1fisicaquimica','profe1fisicaquimica','Profesor/a Física y Química','profesor','profe1fisicaquimica@iesjuanbosco.es'),
('profe1fol','profe1fol','Profesor/a Formación y Orientación Laboral','profesor','profe1fol@iesjuanbosco.es'),
('profe1frances','profe1frances','Profesor/a Francés','profesor','profe1frances@iesjuanbosco.es'),
('profe1geografiahistoria','profe1geografiahistoria','Profesor/a Geografía e Historia','profesor','profe1geografiahistoria@iesjuanbosco.es'),
('profe1ingles','profe1ingles','Profesor/a Inglés','profesor','profe1ingles@iesjuanbosco.es'),
('profe1latingriego','profe1latingriego','Profesor/a Latín y Griego','profesor','profe1latingriego@iesjuanbosco.es'),
('profe1lenguacastellana','profe1lenguacastellana','Profesor/a Lengua Castellana y Literatura','profesor','profe1lenguacastellana@iesjuanbosco.es'),
('profe1matematicas','profe1matematicas','Profesor/a Matemáticas','profesor','profe1matematicas@iesjuanbosco.es'),
('profe1musica','profe1musica','Profesor/a Música','profesor','profe1musica@iesjuanbosco.es'),
('profe1tecnologia','profe1tecnologia','Profesor/a Tecnología','profesor','profe1tecnologia@iesjuanbosco.es'),
('profe1sanidad','profe1sanidad','Profesor/a Sanidad','profesor','profe1sanidad@iesjuanbosco.es'),
('profe1actividadesfisicas','profe1actividadesfisicas','Profesor/a Actividades Físicas y Deportivas','profesor','profe1actividadesfisicas@iesjuanbosco.es'),
('profe1administracion','profe1administracion','Profesor/a Administración','profesor','profe1administracion@iesjuanbosco.es'),
('profe1comercio','profe1comercio','Profesor/a Comercio','profesor','profe1comercio@iesjuanbosco.es'),
('profe1edificacionobracivil','profe1edificacionobracivil','Profesor/a Edificación y Obra Civil','profesor','profe1edificacionobracivil@iesjuanbosco.es'),
('profe1electricidadelectronica','profe1electricidadelectronica','Profesor/a Electricidad y Electrónica','profesor','profe1electricidadelectronica@iesjuanbosco.es'),
('profe1fabricacionmecanica','profe1fabricacionmecanica','Profesor/a Fabricación Mecánica','profesor','profe1fabricacionmecanica@iesjuanbosco.es'),
('profe1imagenpersonal','profe1imagenpersonal','Profesor/a Imagen Personal','profesor','profe1imagenpersonal@iesjuanbosco.es'),
('profe1informatica','profe1informatica','Profesor/a Informática','profesor','profe1informatica@iesjuanbosco.es');
