INSERT OR REPLACE INTO aulas (id,name,icon,desc,th,orden,departamento) VALUES
('aula1','Aula 1','🏫','','th-blue',1,''),
('aula2','Aula 2','🏫','','th-blue',2,''),
('aula3','Aula 3','🏫','','th-blue',3,''),
('aula4','Aula 4','🏫','','th-blue',4,''),
('aula5','Aula 5','🏫','','th-blue',5,''),
('aula6','Aula 6','🏫','','th-blue',6,''),
('aula7','Aula 7','🏫','','th-blue',7,''),
('aula8','Aula 8','🏫','','th-blue',8,''),
('aula9','Aula 9','🏫','','th-blue',9,''),
('aula10','Aula 10','🏫','','th-blue',10,''),
('aula11','Aula 11','🏫','','th-blue',11,''),
('aula12','Aula 12','🏫','','th-blue',12,''),
('aula13','Aula 13','🏫','','th-blue',13,''),
('aula14','Aula 14','🏫','','th-blue',14,''),
('aula15','Aula 15','🏫','','th-blue',15,''),
('aula16','Aula 16','🏫','','th-blue',16,''),
('aula17','Aula 17','🏫','','th-blue',17,''),
('aula18','Aula 18','🏫','','th-blue',18,''),
('aula19','Aula 19','🏫','','th-blue',19,''),
('aula20','Aula 20','🏫','','th-blue',20,''),
('aula21','Aula 21','🏫','','th-blue',21,''),
('aula22','Aula 22','🏫','','th-blue',22,''),
('aula23','Aula 23','🏫','','th-blue',23,''),
('aula24','Aula 24','🏫','','th-blue',24,''),
('aula25','Aula 25','🏫','','th-blue',25,''),
('aula26','Aula 26','🏫','','th-blue',26,''),
('aula27','Aula 27','🏫','','th-blue',27,''),
('aula28','Aula 28','🏫','','th-blue',28,''),
('aula29','Aula 29','🏫','','th-blue',29,''),
('aula30','Aula 30','🏫','','th-blue',30,''),
('aula31','Aula 31','🏫','','th-blue',31,''),
('aula32','Aula 32','🏫','','th-blue',32,''),
('aula33','Aula 33','🏫','','th-blue',33,''),
('aula34','Aula 34','🏫','','th-blue',34,''),
('aula35','Aula 35','🏫','','th-blue',35,''),
('aula36','Aula 36','🏫','','th-blue',36,''),
('aula37','Aula 37','🏫','','th-blue',37,''),
('aula38','Aula 38','🏫','','th-blue',38,''),
('aula39','Aula 39','🏫','','th-blue',39,''),
('aula40','Aula 40','🏫','','th-blue',40,''),
('aula41','Aula 41','🏫','','th-blue',41,''),
('aula42','Aula 42','🏫','','th-blue',42,''),
('aula43','Aula 43','🏫','','th-blue',43,''),
('aula44','Aula 44','🏫','','th-blue',44,''),
('aula45','Aula 45','🏫','','th-blue',45,''),
('aula46','Aula 46','🏫','','th-blue',46,''),
('aula47','Aula 47','🏫','','th-blue',47,''),
('aula48','Aula 48','🏫','','th-blue',48,''),
('aula49','Aula 49','🏫','','th-blue',49,''),
('aula50','Aula 50','🏫','','th-blue',50,''),
('aula51','Aula 51','🏫','','th-blue',51,''),
('aula52','Aula 52','🏫','','th-blue',52,''),
('aula53','Aula 53','🏫','','th-blue',53,''),
('aula54','Aula 54','🏫','','th-blue',54,''),
('aula55','Aula 55','🏫','','th-blue',55,''),
('aula56','Aula 56','🏫','','th-blue',56,''),
('aula57','Aula 57','🏫','','th-blue',57,''),
('aula58','Aula 58','🏫','','th-blue',58,''),
('aula59','Aula 59','🏫','','th-blue',59,''),
('aula60','Aula 60','🏫','','th-blue',60,''),
('aula61','Aula 61','🏫','','th-blue',61,''),
('aula62','Aula 62','🏫','','th-blue',62,''),
('aula63','Aula 63','🏫','','th-blue',63,''),
('aula64','Aula 64','🏫','','th-blue',64,''),
('aula65','Aula 65','🏫','','th-blue',65,''),
('aula66','Aula 66','🏫','','th-blue',66,''),
('aula67','Aula 67','🏫','','th-blue',67,''),
('aula68','Aula 68','🏫','','th-blue',68,''),
('aula69','Aula 69','🏫','','th-blue',69,''),
('aula70','Aula 70','🏫','','th-blue',70,'');

INSERT OR REPLACE INTO aulas (id,name,icon,desc,th,orden,departamento) VALUES
('dept-artesplasticas','Artes Plásticas','🎨','Taller propio del departamento','th-purple',101,'artesplasticas'),
('dept-cienciasnaturales','Ciencias Naturales','🔬','Taller propio del departamento','th-green',102,'cienciasnaturales'),
('dept-economia','Economía','💶','Taller propio del departamento','th-amber',103,'economia'),
('dept-educacionfisicadeportiva','Educación Física y Deportiva','🏃','Taller propio del departamento','th-orange',104,'educacionfisicadeportiva'),
('dept-filosofia','Filosofía','📚','Taller propio del departamento','th-purple',105,'filosofia'),
('dept-fisicaquimica','Física y Química','⚗️','Taller propio del departamento','th-teal',106,'fisicaquimica'),
('dept-fol','Formación y Orientación Laboral','💼','Taller propio del departamento','th-blue',107,'fol'),
('dept-frances','Francés','🇫🇷','Taller propio del departamento','th-blue',108,'frances'),
('dept-geografiahistoria','Geografía e Historia','🗺️','Taller propio del departamento','th-amber',109,'geografiahistoria'),
('dept-ingles','Inglés','🇬🇧','Taller propio del departamento','th-blue',110,'ingles'),
('dept-latingriego','Latín y Griego','🏛️','Taller propio del departamento','th-purple',111,'latingriego'),
('dept-lenguacastellana','Lengua Castellana y Literatura','📖','Taller propio del departamento','th-green',112,'lenguacastellana'),
('dept-matematicas','Matemáticas','📐','Taller propio del departamento','th-blue',113,'matematicas'),
('dept-musica','Música','🎵','Taller propio del departamento','th-purple',114,'musica'),
('dept-tecnologia','Tecnología','⚙️','Taller propio del departamento','th-teal',115,'tecnologia'),
('dept-sanidad','Sanidad','⚕️','Taller propio del departamento','th-green',116,'sanidad'),
('dept-actividadesfisicas','Actividades Físicas y Deportivas','🤸','Taller propio del departamento','th-orange',117,'actividadesfisicas'),
('dept-administracion','Administración','🗂️','Taller propio del departamento','th-amber',118,'administracion'),
('dept-comercio','Comercio','🛒','Taller propio del departamento','th-orange',119,'comercio'),
('dept-edificacionobracivil','Edificación y Obra Civil','🏗️','Taller propio del departamento','th-amber',120,'edificacionobracivil'),
('dept-electricidadelectronica','Electricidad y Electrónica','⚡','Taller propio del departamento','th-purple',121,'electricidadelectronica'),
('dept-fabricacionmecanica','Fabricación Mecánica','🔩','Taller propio del departamento','th-teal',122,'fabricacionmecanica'),
('dept-imagenpersonal','Imagen Personal','💇','Taller propio del departamento','th-orange',123,'imagenpersonal'),
('dept-informatica','Informática','💻','Taller propio del departamento','th-blue',124,'informatica');
