-- Ciclos formativos reales de los departamentos de Formación Profesional
-- (además de Sanidad, ya sembrado en 0009). Un INSERT por departamento.

-- Actividades Físicas y Deportivas: TSEAS + TSAF
INSERT INTO ciclos (cicloId,cicloNombre,nivel,icon,th,desc,modCod,modNombre,modHoras,cicloOrden,modOrden,responsable,departamento) VALUES
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M01','Valoración de la condición física e intervención en accidentes',0,1,1,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M02','Dinamización grupal',0,1,2,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M03','Planificación de la animación sociodeportiva',0,1,3,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M04','Juegos y actividades físico-recreativas y de animación turística',0,1,4,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M05','Actividades físico-deportivas individuales',0,1,5,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M06','Actividades de ocio y tiempo libre',0,1,6,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M07','Actividades físico-deportivas de equipo',0,1,7,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M08','Actividades físico-deportivas de implementos',0,1,8,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M09','Actividades físico-deportivas para la inclusión social',0,1,9,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M10','Metodología de la enseñanza de actividades físico-deportivas',0,1,10,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M11','Actividades de acondicionamiento físico',0,1,11,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M12','Digitalización aplicada al sistema productivo (1.º-TSEAS)',0,1,12,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M13','Sostenibilidad aplicada al sistema productivo (1.º-TSEAS)',0,1,13,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M14','Itinerario personal para la empleabilidad I (1.º-TSEAS)',0,1,14,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M15','Itinerario personal para la empleabilidad II (2.º-TSEAS)',0,1,15,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M16','Proyecto intermodular de Enseñanza y Animación Sociodeportiva (2.º-TSEAS)',0,1,16,'','actividadesfisicas'),
('tseas','Técnico Superior en Enseñanza y Animación Sociodeportiva (TSEAS)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M17','Fase de formación en empresa (2.º-TSEAS)',0,1,17,'','actividadesfisicas'),

('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M01','Valoración de la condición física',0,2,1,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M02','Fitness en sala de entrenamiento polivalente',0,2,2,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M03','Actividades básicas de acondicionamiento físico con soporte musical',0,2,3,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M04','Acondicionamiento físico en el agua',0,2,4,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M05','Técnicas de hidrocinesia',0,2,5,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M06','Control postural, bienestar y mantenimiento funcional',0,2,6,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M07','Actividades especializadas de acondicionamiento físico',0,2,7,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M08','Empresa e iniciativa relacionada con el sector',0,2,8,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M09','Digitalización aplicada al sistema productivo (1.º-TSAF)',0,2,9,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M10','Sostenibilidad aplicada al sistema productivo (1.º-TSAF)',0,2,10,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M11','Itinerario personal para la empleabilidad I (1.º-TSAF)',0,2,11,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M12','Itinerario personal para la empleabilidad II (2.º-TSAF)',0,2,12,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M13','Proyecto intermodular de Acondicionamiento Físico (2.º-TSAF)',0,2,13,'','actividadesfisicas'),
('tsaf','Técnico Superior en Acondicionamiento Físico (TSAF)','CFGS','🤸','th-orange','Grado Superior · Actividades Físicas y Deportivas','M14','Fase de formación en empresa (2.º-TSAF)',0,2,14,'','actividadesfisicas');

-- Administración: GA + AF + AD
INSERT INTO ciclos (cicloId,cicloNombre,nivel,icon,th,desc,modCod,modNombre,modHoras,cicloOrden,modOrden,responsable,departamento) VALUES
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M01','Comunicación empresarial y atención al cliente',0,1,1,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M02','Operaciones administrativas de compra-venta',0,1,2,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M03','Empresa y Administración',0,1,3,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M04','Tratamiento informático de la información',0,1,4,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M05','Técnica contable',0,1,5,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M06','Operaciones administrativas de recursos humanos',0,1,6,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M07','Tratamiento de la documentación contable',0,1,7,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M08','Empresa en el aula',0,1,8,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M09','Operaciones auxiliares de gestión de tesorería',0,1,9,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M10','Inglés profesional',0,1,10,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M11','Digitalización aplicada al sistema productivo (1.º-GA)',0,1,11,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M12','Sostenibilidad aplicada al sistema productivo (1.º-GA)',0,1,12,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M13','Itinerario personal para la empleabilidad I (1.º-GA)',0,1,13,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M14','Itinerario personal para la empleabilidad II (2.º-GA)',0,1,14,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M15','Proyecto intermodular de Gestión Administrativa (2.º-GA)',0,1,15,'','administracion'),
('ga','Técnico en Gestión Administrativa (GA)','CFGM','🗂️','th-amber','Grado Medio · Administración','M16','Fase de formación en empresa (2.º-GA)',0,1,16,'','administracion'),

('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M01','Gestión de la documentación jurídica y empresarial',0,2,1,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M02','Recursos humanos y responsabilidad social corporativa',0,2,2,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M03','Ofimática y proceso de la información',0,2,3,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M04','Proceso integral de la actividad comercial',0,2,4,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M05','Comunicación y atención al cliente',0,2,5,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M06','Gestión de recursos humanos',0,2,6,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M07','Gestión financiera',0,2,7,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M08','Contabilidad y fiscalidad',0,2,8,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M09','Gestión logística y comercial',0,2,9,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M10','Simulación empresarial',0,2,10,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M11','Inglés profesional',0,2,11,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M12','Digitalización aplicada al sistema productivo (1.º-AF)',0,2,12,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M13','Sostenibilidad aplicada al sistema productivo (1.º-AF)',0,2,13,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M14','Itinerario personal para la empleabilidad I (1.º-AF)',0,2,14,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M15','Itinerario personal para la empleabilidad II (2.º-AF)',0,2,15,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M16','Proyecto intermodular de Administración y Finanzas (2.º-AF)',0,2,16,'','administracion'),
('af','Técnico Superior en Administración y Finanzas (AF)','CFGS','🗂️','th-amber','Grado Superior · Administración','M17','Fase de formación en empresa (2.º-AF)',0,2,17,'','administracion'),

('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M01','Gestión de la documentación jurídica y empresarial',0,3,1,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M02','Recursos humanos y responsabilidad social corporativa',0,3,2,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M03','Ofimática y proceso de la información',0,3,3,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M04','Proceso integral de la actividad comercial',0,3,4,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M05','Comunicación y atención al cliente',0,3,5,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M06','Organización de eventos empresariales',0,3,6,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M07','Protocolo empresarial',0,3,7,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M08','Segunda lengua extranjera',0,3,8,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M09','Inglés profesional',0,3,9,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M10','Digitalización aplicada al sistema productivo (1.º-AD)',0,3,10,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M11','Sostenibilidad aplicada al sistema productivo (1.º-AD)',0,3,11,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M12','Itinerario personal para la empleabilidad I (1.º-AD)',0,3,12,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M13','Itinerario personal para la empleabilidad II (2.º-AD)',0,3,13,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M14','Proyecto intermodular de Asistencia a la Dirección (2.º-AD)',0,3,14,'','administracion'),
('ad','Técnico Superior en Asistencia a la Dirección (AD)','CFGS','🗂️','th-amber','Grado Superior · Administración','M15','Fase de formación en empresa (2.º-AD)',0,3,15,'','administracion');

-- Comercio: AC + GVEC
INSERT INTO ciclos (cicloId,cicloNombre,nivel,icon,th,desc,modCod,modNombre,modHoras,cicloOrden,modOrden,responsable,departamento) VALUES
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M01','Marketing en la actividad comercial',0,1,1,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M02','Gestión de un pequeño comercio',0,1,2,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M03','Técnicas de almacén',0,1,3,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M04','Gestión de compras',0,1,4,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M05','Venta técnica',0,1,5,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M06','Dinamización del punto de venta',0,1,6,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M07','Procesos de venta',0,1,7,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M08','Aplicaciones informáticas para el comercio',0,1,8,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M09','Servicios de atención comercial',0,1,9,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M10','Comercio electrónico',0,1,10,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M11','Inglés profesional',0,1,11,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M12','Digitalización aplicada al sistema productivo (1.º-AC)',0,1,12,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M13','Sostenibilidad aplicada al sistema productivo (1.º-AC)',0,1,13,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M14','Itinerario personal para la empleabilidad I (1.º-AC)',0,1,14,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M15','Itinerario personal para la empleabilidad II (2.º-AC)',0,1,15,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M16','Proyecto intermodular de Actividades Comerciales (2.º-AC)',0,1,16,'','comercio'),
('ac','Técnico en Actividades Comerciales (AC)','CFGM','🛒','th-orange','Grado Medio · Comercio','M17','Fase de formación en empresa (2.º-AC)',0,1,17,'','comercio'),

('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M01','Escaparatismo y diseño de espacios comerciales',0,2,1,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M02','Gestión de productos y promociones',0,2,2,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M03','Organización de equipos de ventas',0,2,3,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M04','Técnicas de venta y negociación',0,2,4,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M05','Investigación comercial',0,2,5,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M06','Marketing digital',0,2,6,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M07','Logística de almacenamiento',0,2,7,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M08','Políticas de marketing',0,2,8,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M09','Inglés profesional',0,2,9,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M10','Digitalización aplicada al sistema productivo (1.º-GVEC)',0,2,10,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M11','Sostenibilidad aplicada al sistema productivo (1.º-GVEC)',0,2,11,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M12','Itinerario personal para la empleabilidad I (1.º-GVEC)',0,2,12,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M13','Itinerario personal para la empleabilidad II (2.º-GVEC)',0,2,13,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M14','Proyecto intermodular de Gestión de Ventas y Espacios Comerciales (2.º-GVEC)',0,2,14,'','comercio'),
('gvec','Técnico Superior en Gestión de Ventas y Espacios Comerciales (GVEC)','CFGS','🛒','th-orange','Grado Superior · Comercio','M15','Fase de formación en empresa (2.º-GVEC)',0,2,15,'','comercio');

-- Edificación y Obra Civil: TPE
INSERT INTO ciclos (cicloId,cicloNombre,nivel,icon,th,desc,modCod,modNombre,modHoras,cicloOrden,modOrden,responsable,departamento) VALUES
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M01','Estructuras de construcción',0,1,1,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M02','Representaciones de construcción',0,1,2,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M03','Replanteos de construcción',0,1,3,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M04','Diseño y construcción de edificios',0,1,4,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M05','Instalaciones en edificación',0,1,5,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M06','Mediciones y valoraciones',0,1,6,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M07','Planificación de construcción',0,1,7,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M08','Eficiencia energética en edificación',0,1,8,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M09','Desarrollo de proyectos de edificación residencial',0,1,9,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M10','Desarrollo de proyectos de edificación no residencial',0,1,10,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M11','Digitalización aplicada al sistema productivo (1.º-TPE)',0,1,11,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M12','Sostenibilidad aplicada al sistema productivo (1.º-TPE)',0,1,12,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M13','Itinerario personal para la empleabilidad I (1.º-TPE)',0,1,13,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M14','Itinerario personal para la empleabilidad II (2.º-TPE)',0,1,14,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M15','Proyecto intermodular de Proyectos de Edificación (2.º-TPE)',0,1,15,'','edificacionobracivil'),
('tpe','Técnico Superior en Proyectos de Edificación (TPE)','CFGS','🏗️','th-amber','Grado Superior · Edificación y Obra Civil','M16','Fase de formación en empresa (2.º-TPE)',0,1,16,'','edificacionobracivil');

-- Electricidad y Electrónica: IT + IEA + MELE + SEA
INSERT INTO ciclos (cicloId,cicloNombre,nivel,icon,th,desc,modCod,modNombre,modHoras,cicloOrden,modOrden,responsable,departamento) VALUES
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M01','Infraestructuras comunes de telecomunicación en viviendas y edificios',0,1,1,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M02','Instalaciones domóticas',0,1,2,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M03','Electrónica aplicada',0,1,3,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M04','Equipos microinformáticos',0,1,4,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M05','Infraestructuras de redes de datos y sistemas de telefonía',0,1,5,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M06','Instalaciones de megafonía y sonorización',0,1,6,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M07','Circuito cerrado de televisión y seguridad electrónica',0,1,7,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M08','Instalaciones eléctricas básicas',0,1,8,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M09','Digitalización aplicada al sistema productivo (1.º-IT)',0,1,9,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M10','Sostenibilidad aplicada al sistema productivo (1.º-IT)',0,1,10,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M11','Itinerario personal para la empleabilidad I (1.º-IT)',0,1,11,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M12','Itinerario personal para la empleabilidad II (2.º-IT)',0,1,12,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M13','Proyecto intermodular de Instalaciones de Telecomunicaciones (2.º-IT)',0,1,13,'','electricidadelectronica'),
('it','Técnico en Instalaciones de Telecomunicaciones (IT)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M14','Fase de formación en empresa (2.º-IT)',0,1,14,'','electricidadelectronica'),

('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M01','Automatismos industriales',0,2,1,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M02','Electrónica',0,2,2,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M03','Electrotecnia',0,2,3,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M04','Instalaciones eléctricas interiores',0,2,4,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M05','Instalaciones de distribución',0,2,5,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M06','Infraestructuras comunes de telecomunicaciones',0,2,6,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M07','Instalaciones domóticas',0,2,7,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M08','Máquinas eléctricas',0,2,8,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M09','Energías renovables',0,2,9,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M10','Digitalización aplicada al sistema productivo (1.º-IEA)',0,2,10,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M11','Sostenibilidad aplicada al sistema productivo (1.º-IEA)',0,2,11,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M12','Itinerario personal para la empleabilidad I (1.º-IEA)',0,2,12,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M13','Itinerario personal para la empleabilidad II (2.º-IEA)',0,2,13,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M14','Proyecto intermodular de Instalaciones Eléctricas y Automáticas (2.º-IEA)',0,2,14,'','electricidadelectronica'),
('iea','Técnico en Instalaciones Eléctricas y Automáticas (IEA)','CFGM','⚡','th-purple','Grado Medio · Electricidad y Electrónica','M15','Fase de formación en empresa (2.º-IEA)',0,2,15,'','electricidadelectronica'),

('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M01','Circuitos electrónicos analógicos',0,3,1,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M02','Equipos microprogramables',0,3,2,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M03','Electrónica de potencia',0,3,3,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M04','Equipos de radiocomunicaciones',0,3,4,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M05','Sistemas de audio',0,3,5,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M06','Sistemas de vídeo',0,3,6,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M07','Técnicas y procesos de montaje y mantenimiento',0,3,7,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M08','Infraestructuras y desarrollo del mantenimiento electrónico',0,3,8,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M09','Digitalización aplicada al sistema productivo (1.º-MELE)',0,3,9,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M10','Sostenibilidad aplicada al sistema productivo (1.º-MELE)',0,3,10,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M11','Itinerario personal para la empleabilidad I (1.º-MELE)',0,3,11,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M12','Itinerario personal para la empleabilidad II (2.º-MELE)',0,3,12,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M13','Proyecto intermodular de Mantenimiento Electrónico (2.º-MELE)',0,3,13,'','electricidadelectronica'),
('mele','Técnico Superior en Mantenimiento Electrónico (MELE)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M14','Fase de formación en empresa (2.º-MELE)',0,3,14,'','electricidadelectronica'),

('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M01','Configuración de instalaciones domóticas y automáticas',0,4,1,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M02','Configuración de instalaciones eléctricas',0,4,2,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M03','Procesos en instalaciones de infraestructuras comunes de telecomunicaciones',0,4,3,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M04','Técnicas y procesos en instalaciones eléctricas',0,4,4,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M05','Documentación técnica',0,4,5,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M06','Desarrollo de redes eléctricas y centros de transformación',0,4,6,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M07','Gestión del montaje y mantenimiento',0,4,7,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M08','Digitalización aplicada al sistema productivo (1.º-SEA)',0,4,8,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M09','Sostenibilidad aplicada al sistema productivo (1.º-SEA)',0,4,9,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M10','Itinerario personal para la empleabilidad I (1.º-SEA)',0,4,10,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M11','Itinerario personal para la empleabilidad II (2.º-SEA)',0,4,11,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M12','Proyecto intermodular de Sistemas Electrotécnicos y Automatizados (2.º-SEA)',0,4,12,'','electricidadelectronica'),
('sea','Técnico Superior en Sistemas Electrotécnicos y Automatizados (SEA)','CFGS','⚡','th-purple','Grado Superior · Electricidad y Electrónica','M13','Fase de formación en empresa (2.º-SEA)',0,4,13,'','electricidadelectronica');

-- Fabricación Mecánica: MEC + PPFM
INSERT INTO ciclos (cicloId,cicloNombre,nivel,icon,th,desc,modCod,modNombre,modHoras,cicloOrden,modOrden,responsable,departamento) VALUES
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M01','Procesos de mecanizado',0,1,1,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M02','Fabricación por arranque de viruta',0,1,2,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M03','Fabricación por abrasión',0,1,3,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M04','Sistemas automatizados',0,1,4,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M05','Interpretación gráfica',0,1,5,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M06','Metrología y ensayos',0,1,6,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M07','Mecanizado por control numérico',0,1,7,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M08','Digitalización aplicada al sistema productivo (1.º-MEC)',0,1,8,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M09','Sostenibilidad aplicada al sistema productivo (1.º-MEC)',0,1,9,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M10','Itinerario personal para la empleabilidad I (1.º-MEC)',0,1,10,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M11','Itinerario personal para la empleabilidad II (2.º-MEC)',0,1,11,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M12','Proyecto intermodular de Mecanizado (2.º-MEC)',0,1,12,'','fabricacionmecanica'),
('mec','Técnico en Mecanizado (MEC)','CFGM','🔩','th-teal','Grado Medio · Fabricación Mecánica','M13','Fase de formación en empresa (2.º-MEC)',0,1,13,'','fabricacionmecanica'),

('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M01','Interpretación gráfica',0,2,1,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M02','Definición de procesos de mecanizado',0,2,2,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M03','Programación de sistemas automáticos',0,2,3,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M04','Programación de la producción',0,2,4,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M05','Ejecución de procesos de fabricación',0,2,5,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M06','Fabricación asistida por ordenador',0,2,6,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M07','Gestión de la calidad',0,2,7,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M08','Verificación de productos',0,2,8,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M09','Digitalización aplicada al sistema productivo (1.º-PPFM)',0,2,9,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M10','Sostenibilidad aplicada al sistema productivo (1.º-PPFM)',0,2,10,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M11','Itinerario personal para la empleabilidad I (1.º-PPFM)',0,2,11,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M12','Itinerario personal para la empleabilidad II (2.º-PPFM)',0,2,12,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M13','Proyecto intermodular de Programación de la Producción en Fabricación Mecánica (2.º-PPFM)',0,2,13,'','fabricacionmecanica'),
('ppfm','Técnico Superior en Programación de la Producción en Fabricación Mecánica (PPFM)','CFGS','🔩','th-teal','Grado Superior · Fabricación Mecánica','M14','Fase de formación en empresa (2.º-PPFM)',0,2,14,'','fabricacionmecanica');

-- Imagen Personal: EB + PCC + EDP
INSERT INTO ciclos (cicloId,cicloNombre,nivel,icon,th,desc,modCod,modNombre,modHoras,cicloOrden,modOrden,responsable,departamento) VALUES
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M01','Técnicas de higiene facial y corporal',0,1,1,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M02','Maquillaje',0,1,2,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M03','Depilación mecánica y decoloración',0,1,3,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M04','Estética de manos y pies',0,1,4,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M05','Técnicas de uñas artificiales',0,1,5,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M06','Análisis estético',0,1,6,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M07','Actividades en cabina de estética',0,1,7,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M08','Cosmetología',0,1,8,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M09','Perfumería y cosmética natural',0,1,9,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M10','Digitalización aplicada al sistema productivo (1.º-EB)',0,1,10,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M11','Sostenibilidad aplicada al sistema productivo (1.º-EB)',0,1,11,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M12','Itinerario personal para la empleabilidad I (1.º-EB)',0,1,12,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M13','Itinerario personal para la empleabilidad II (2.º-EB)',0,1,13,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M14','Proyecto intermodular de Estética y Belleza (2.º-EB)',0,1,14,'','imagenpersonal'),
('eb','Técnico en Estética y Belleza (EB)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M15','Fase de formación en empresa (2.º-EB)',0,1,15,'','imagenpersonal'),

('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M01','Peinados y recogidos',0,2,1,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M02','Coloración capilar',0,2,2,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M03','Cosmética para peluquería',0,2,3,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M04','Técnicas de corte del cabello',0,2,4,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M05','Cambios de forma permanente',0,2,5,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M06','Peluquería y estilismo masculino',0,2,6,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M07','Análisis capilar',0,2,7,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M08','Estética de manos y pies',0,2,8,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M09','Imagen corporal y hábitos saludables',0,2,9,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M10','Digitalización aplicada al sistema productivo (1.º-PCC)',0,2,10,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M11','Sostenibilidad aplicada al sistema productivo (1.º-PCC)',0,2,11,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M12','Itinerario personal para la empleabilidad I (1.º-PCC)',0,2,12,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M13','Itinerario personal para la empleabilidad II (2.º-PCC)',0,2,13,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M14','Proyecto intermodular de Peluquería y Cosmética Capilar (2.º-PCC)',0,2,14,'','imagenpersonal'),
('pcc','Técnico en Peluquería y Cosmética Capilar (PCC)','CFGM','💇','th-orange','Grado Medio · Imagen Personal','M15','Fase de formación en empresa (2.º-PCC)',0,2,15,'','imagenpersonal'),

('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M01','Dermotricología',0,3,1,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M02','Recursos técnicos y cosméticos',0,3,2,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M03','Tratamientos capilares',0,3,3,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M04','Procesos fisiológicos y de higiene en imagen personal',0,3,4,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M05','Organización y gestión de empresas de imagen personal',0,3,5,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M06','Estilismo en peluquería',0,3,6,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M07','Dirección técnico-artística',0,3,7,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M08','Marketing y venta',0,3,8,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M09','Digitalización aplicada al sistema productivo (1.º-EDP)',0,3,9,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M10','Sostenibilidad aplicada al sistema productivo (1.º-EDP)',0,3,10,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M11','Itinerario personal para la empleabilidad I (1.º-EDP)',0,3,11,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M12','Itinerario personal para la empleabilidad II (2.º-EDP)',0,3,12,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M13','Proyecto intermodular de Estilismo y Dirección de Peluquería (2.º-EDP)',0,3,13,'','imagenpersonal'),
('edp','Técnico Superior en Estilismo y Dirección de Peluquería (EDP)','CFGS','💇','th-orange','Grado Superior · Imagen Personal','M14','Fase de formación en empresa (2.º-EDP)',0,3,14,'','imagenpersonal');

-- Informática: SMR + ASIR + DAW + DAM + CETI (curso de especialización)
INSERT INTO ciclos (cicloId,cicloNombre,nivel,icon,th,desc,modCod,modNombre,modHoras,cicloOrden,modOrden,responsable,departamento) VALUES
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M01','Montaje y mantenimiento de equipos',0,1,1,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M02','Sistemas operativos monopuesto',0,1,2,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M03','Aplicaciones ofimáticas',0,1,3,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M04','Redes locales',0,1,4,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M05','Sistemas operativos en red',0,1,5,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M06','Seguridad informática',0,1,6,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M07','Servicios en red',0,1,7,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M08','Aplicaciones web',0,1,8,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M09','Digitalización aplicada al sistema productivo (1.º-SMR)',0,1,9,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M10','Sostenibilidad aplicada al sistema productivo (1.º-SMR)',0,1,10,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M11','Itinerario personal para la empleabilidad I (1.º-SMR)',0,1,11,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M12','Itinerario personal para la empleabilidad II (2.º-SMR)',0,1,12,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M13','Proyecto intermodular de Sistemas Microinformáticos y Redes (2.º-SMR)',0,1,13,'','informatica'),
('smr','Técnico en Sistemas Microinformáticos y Redes (SMR)','CFGM','💻','th-blue','Grado Medio · Informática','M14','Fase de formación en empresa (2.º-SMR)',0,1,14,'','informatica'),

('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M01','Implantación de sistemas operativos',0,2,1,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M02','Planificación y administración de redes',0,2,2,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M03','Fundamentos de hardware',0,2,3,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M04','Gestión de bases de datos',0,2,4,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M05','Administración de sistemas operativos',0,2,5,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M06','Servicios de red e Internet',0,2,6,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M07','Implantación de aplicaciones web',0,2,7,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M08','Administración de sistemas gestores de bases de datos',0,2,8,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M09','Seguridad y alta disponibilidad',0,2,9,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M10','Digitalización aplicada al sistema productivo (1.º-ASIR)',0,2,10,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M11','Sostenibilidad aplicada al sistema productivo (1.º-ASIR)',0,2,11,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M12','Itinerario personal para la empleabilidad I (1.º-ASIR)',0,2,12,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M13','Itinerario personal para la empleabilidad II (2.º-ASIR)',0,2,13,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M14','Proyecto intermodular de Administración de Sistemas Informáticos en Red (2.º-ASIR)',0,2,14,'','informatica'),
('asir','Técnico Superior en Administración de Sistemas Informáticos en Red (ASIR)','CFGS','💻','th-blue','Grado Superior · Informática','M15','Fase de formación en empresa (2.º-ASIR)',0,2,15,'','informatica'),

('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M01','Sistemas informáticos',0,3,1,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M02','Bases de datos',0,3,2,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M03','Programación',0,3,3,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M04','Lenguajes de marcas',0,3,4,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M05','Entornos de desarrollo',0,3,5,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M06','Desarrollo web en entorno cliente',0,3,6,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M07','Desarrollo web en entorno servidor',0,3,7,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M08','Despliegue de aplicaciones web',0,3,8,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M09','Diseño de interfaces web',0,3,9,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M10','Digitalización aplicada al sistema productivo (1.º-DAW)',0,3,10,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M11','Sostenibilidad aplicada al sistema productivo (1.º-DAW)',0,3,11,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M12','Itinerario personal para la empleabilidad I (1.º-DAW)',0,3,12,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M13','Itinerario personal para la empleabilidad II (2.º-DAW)',0,3,13,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M14','Proyecto intermodular de Desarrollo de Aplicaciones Web (2.º-DAW)',0,3,14,'','informatica'),
('daw','Técnico Superior en Desarrollo de Aplicaciones Web (DAW)','CFGS','💻','th-blue','Grado Superior · Informática','M15','Fase de formación en empresa (2.º-DAW)',0,3,15,'','informatica'),

('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M01','Sistemas informáticos',0,4,1,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M02','Bases de datos',0,4,2,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M03','Programación',0,4,3,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M04','Lenguajes de marcas',0,4,4,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M05','Entornos de desarrollo',0,4,5,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M06','Acceso a datos',0,4,6,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M07','Desarrollo de interfaces',0,4,7,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M08','Programación multimedia y dispositivos móviles',0,4,8,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M09','Programación de servicios y procesos',0,4,9,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M10','Sistemas de gestión empresarial',0,4,10,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M11','Digitalización aplicada al sistema productivo (1.º-DAM)',0,4,11,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M12','Sostenibilidad aplicada al sistema productivo (1.º-DAM)',0,4,12,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M13','Itinerario personal para la empleabilidad I (1.º-DAM)',0,4,13,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M14','Itinerario personal para la empleabilidad II (2.º-DAM)',0,4,14,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M15','Proyecto intermodular de Desarrollo de Aplicaciones Multiplataforma (2.º-DAM)',0,4,15,'','informatica'),
('dam','Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (DAM)','CFGS','💻','th-blue','Grado Superior · Informática','M16','Fase de formación en empresa (2.º-DAM)',0,4,16,'','informatica'),

('ceti','Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información (CETI)','CE','💻','th-blue','Curso de Especialización · Informática','M01','Incidentes de ciberseguridad',0,5,1,'','informatica'),
('ceti','Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información (CETI)','CE','💻','th-blue','Curso de Especialización · Informática','M02','Bastionado de redes y sistemas',0,5,2,'','informatica'),
('ceti','Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información (CETI)','CE','💻','th-blue','Curso de Especialización · Informática','M03','Puesta en producción segura',0,5,3,'','informatica'),
('ceti','Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información (CETI)','CE','💻','th-blue','Curso de Especialización · Informática','M04','Análisis forense informático',0,5,4,'','informatica'),
('ceti','Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información (CETI)','CE','💻','th-blue','Curso de Especialización · Informática','M05','Hacking ético',0,5,5,'','informatica'),
('ceti','Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información (CETI)','CE','💻','th-blue','Curso de Especialización · Informática','M06','Normativa de ciberseguridad',0,5,6,'','informatica'),
('ceti','Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información (CETI)','CE','💻','th-blue','Curso de Especialización · Informática','M07','Proyecto de ciberseguridad',0,5,7,'','informatica');
