-- Migración 0016: pantalla multimedia + pizarra de tiza en las 70 aulas
-- genéricas del centro, e ítems inventados en cada aula propia de departamento.

INSERT INTO inventario (ref,aula,mod,item,qty,min,cat,loc,est,fecha,code,departamento) VALUES
('IB','aula1','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00001',''),
('IB','aula1','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00002',''),
('IB','aula2','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00003',''),
('IB','aula2','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00004',''),
('IB','aula3','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00005',''),
('IB','aula3','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00006',''),
('IB','aula4','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00007',''),
('IB','aula4','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00008',''),
('IB','aula5','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00009',''),
('IB','aula5','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00010',''),
('IB','aula6','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00011',''),
('IB','aula6','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00012',''),
('IB','aula7','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00013',''),
('IB','aula7','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00014',''),
('IB','aula8','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00015',''),
('IB','aula8','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00016',''),
('IB','aula9','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00017',''),
('IB','aula9','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00018',''),
('IB','aula10','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00019',''),
('IB','aula10','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00020',''),
('IB','aula11','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00021',''),
('IB','aula11','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00022',''),
('IB','aula12','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00023',''),
('IB','aula12','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00024',''),
('IB','aula13','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00025',''),
('IB','aula13','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00026',''),
('IB','aula14','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00027',''),
('IB','aula14','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00028',''),
('IB','aula15','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00029',''),
('IB','aula15','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00030',''),
('IB','aula16','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00031',''),
('IB','aula16','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00032',''),
('IB','aula17','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00033',''),
('IB','aula17','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00034',''),
('IB','aula18','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00035',''),
('IB','aula18','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00036',''),
('IB','aula19','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00037',''),
('IB','aula19','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00038',''),
('IB','aula20','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00039',''),
('IB','aula20','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00040',''),
('IB','aula21','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00041',''),
('IB','aula21','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00042',''),
('IB','aula22','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00043',''),
('IB','aula22','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00044',''),
('IB','aula23','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00045',''),
('IB','aula23','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00046',''),
('IB','aula24','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00047',''),
('IB','aula24','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00048',''),
('IB','aula25','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00049',''),
('IB','aula25','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00050',''),
('IB','aula26','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00051',''),
('IB','aula26','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00052',''),
('IB','aula27','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00053',''),
('IB','aula27','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00054',''),
('IB','aula28','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00055',''),
('IB','aula28','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00056',''),
('IB','aula29','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00057',''),
('IB','aula29','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00058',''),
('IB','aula30','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00059',''),
('IB','aula30','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00060',''),
('IB','aula31','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00061',''),
('IB','aula31','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00062',''),
('IB','aula32','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00063',''),
('IB','aula32','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00064',''),
('IB','aula33','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00065',''),
('IB','aula33','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00066',''),
('IB','aula34','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00067',''),
('IB','aula34','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00068',''),
('IB','aula35','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00069',''),
('IB','aula35','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00070',''),
('IB','aula36','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00071',''),
('IB','aula36','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00072',''),
('IB','aula37','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00073',''),
('IB','aula37','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00074',''),
('IB','aula38','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00075',''),
('IB','aula38','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00076',''),
('IB','aula39','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00077',''),
('IB','aula39','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00078',''),
('IB','aula40','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00079',''),
('IB','aula40','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00080',''),
('IB','aula41','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00081',''),
('IB','aula41','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00082',''),
('IB','aula42','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00083',''),
('IB','aula42','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00084',''),
('IB','aula43','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00085',''),
('IB','aula43','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00086',''),
('IB','aula44','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00087',''),
('IB','aula44','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00088',''),
('IB','aula45','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00089',''),
('IB','aula45','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00090',''),
('IB','aula46','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00091',''),
('IB','aula46','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00092',''),
('IB','aula47','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00093',''),
('IB','aula47','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00094',''),
('IB','aula48','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00095',''),
('IB','aula48','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00096',''),
('IB','aula49','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00097',''),
('IB','aula49','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00098',''),
('IB','aula50','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00099',''),
('IB','aula50','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00100',''),
('IB','aula51','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00101',''),
('IB','aula51','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00102',''),
('IB','aula52','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00103',''),
('IB','aula52','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00104',''),
('IB','aula53','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00105',''),
('IB','aula53','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00106',''),
('IB','aula54','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00107',''),
('IB','aula54','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00108',''),
('IB','aula55','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00109',''),
('IB','aula55','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00110',''),
('IB','aula56','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00111',''),
('IB','aula56','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00112',''),
('IB','aula57','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00113',''),
('IB','aula57','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00114',''),
('IB','aula58','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00115',''),
('IB','aula58','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00116',''),
('IB','aula59','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00117',''),
('IB','aula59','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00118',''),
('IB','aula60','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00119',''),
('IB','aula60','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00120',''),
('IB','aula61','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00121',''),
('IB','aula61','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00122',''),
('IB','aula62','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00123',''),
('IB','aula62','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00124',''),
('IB','aula63','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00125',''),
('IB','aula63','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00126',''),
('IB','aula64','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00127',''),
('IB','aula64','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00128',''),
('IB','aula65','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00129',''),
('IB','aula65','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00130',''),
('IB','aula66','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00131',''),
('IB','aula66','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00132',''),
('IB','aula67','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00133',''),
('IB','aula67','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00134',''),
('IB','aula68','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00135',''),
('IB','aula68','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00136',''),
('IB','aula69','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00137',''),
('IB','aula69','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00138',''),
('IB','aula70','','Pantalla multimedia',1,1,'Audiovisual','Pared frontal','Bueno','','IB-00139',''),
('IB','aula70','','Pizarra de tiza',1,1,'Mobiliario','Pared frontal','Bueno','','IB-00140','');

INSERT INTO inventario (ref,aula,mod,item,qty,min,cat,loc,est,fecha,code,departamento) VALUES
('IB','dept-artesplasticas','','Caballete de madera',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00141','artesplasticas'),
('IB','dept-artesplasticas','','Set de pinceles',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00142','artesplasticas'),
('IB','dept-artesplasticas','','Caja de témperas',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00143','artesplasticas'),
('IB','dept-artesplasticas','','Torno de alfarero',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00144','artesplasticas'),
('IB','dept-cienciasnaturales','','Microscopio óptico',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00145','cienciasnaturales'),
('IB','dept-cienciasnaturales','','Kit de disección',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00146','cienciasnaturales'),
('IB','dept-cienciasnaturales','','Modelo anatómico torso',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00147','cienciasnaturales'),
('IB','dept-cienciasnaturales','','Lupa binocular',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00148','cienciasnaturales'),
('IB','dept-economia','','Calculadora financiera',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00149','economia'),
('IB','dept-economia','','Pizarra digital',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00150','economia'),
('IB','dept-economia','','Proyector portátil',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00151','economia'),
('IB','dept-educacionfisicadeportiva','','Balón de baloncesto',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00152','educacionfisicadeportiva'),
('IB','dept-educacionfisicadeportiva','','Colchoneta de gimnasia',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00153','educacionfisicadeportiva'),
('IB','dept-educacionfisicadeportiva','','Cronómetro digital',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00154','educacionfisicadeportiva'),
('IB','dept-educacionfisicadeportiva','','Red de voleibol',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00155','educacionfisicadeportiva'),
('IB','dept-filosofia','','Proyector de diapositivas',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00156','filosofia'),
('IB','dept-filosofia','','Colección de textos filosóficos',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00157','filosofia'),
('IB','dept-filosofia','','Altavoz portátil',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00158','filosofia'),
('IB','dept-fisicaquimica','','Balanza de precisión',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00159','fisicaquimica'),
('IB','dept-fisicaquimica','','Kit de laboratorio químico',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00160','fisicaquimica'),
('IB','dept-fisicaquimica','','Mechero Bunsen',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00161','fisicaquimica'),
('IB','dept-fisicaquimica','','Bata de laboratorio',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00162','fisicaquimica'),
('IB','dept-fol','','Ordenador portátil',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00163','fol'),
('IB','dept-fol','','Impresora multifunción',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00164','fol'),
('IB','dept-fol','','Archivador metálico',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00165','fol'),
('IB','dept-frances','','Reproductor de audio',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00166','frances'),
('IB','dept-frances','','Diccionario francés-español',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00167','frances'),
('IB','dept-frances','','Mapa mudo de Francia',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00168','frances'),
('IB','dept-geografiahistoria','','Mapa mural de España',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00169','geografiahistoria'),
('IB','dept-geografiahistoria','','Globo terráqueo',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00170','geografiahistoria'),
('IB','dept-geografiahistoria','','Atlas histórico',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00171','geografiahistoria'),
('IB','dept-ingles','','Reproductor de audio',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00172','ingles'),
('IB','dept-ingles','','Diccionario inglés-español',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00173','ingles'),
('IB','dept-ingles','','Set de tarjetas didácticas',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00174','ingles'),
('IB','dept-latingriego','','Mapa del Imperio Romano',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00175','latingriego'),
('IB','dept-latingriego','','Diccionario latín-español',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00176','latingriego'),
('IB','dept-latingriego','','Réplica de ánfora',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00177','latingriego'),
('IB','dept-lenguacastellana','','Diccionario de la RAE',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00178','lenguacastellana'),
('IB','dept-lenguacastellana','','Colección de clásicos',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00179','lenguacastellana'),
('IB','dept-lenguacastellana','','Pizarra digital',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00180','lenguacastellana'),
('IB','dept-matematicas','','Juego de geometría mural',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00181','matematicas'),
('IB','dept-matematicas','','Calculadora científica',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00182','matematicas'),
('IB','dept-matematicas','','Ábaco didáctico',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00183','matematicas'),
('IB','dept-musica','','Teclado electrónico',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00184','musica'),
('IB','dept-musica','','Guitarra española',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00185','musica'),
('IB','dept-musica','','Set de percusión',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00186','musica'),
('IB','dept-musica','','Atril de partituras',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00187','musica'),
('IB','dept-tecnologia','','Kit de robótica educativa',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00188','tecnologia'),
('IB','dept-tecnologia','','Impresora 3D',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00189','tecnologia'),
('IB','dept-tecnologia','','Placa Arduino',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00190','tecnologia'),
('IB','dept-tecnologia','','Caja de herramientas',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00191','tecnologia'),
('IB','dept-sanidad','','Maniquí de prácticas',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00192','sanidad'),
('IB','dept-sanidad','','Camilla de exploración',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00193','sanidad'),
('IB','dept-sanidad','','Tensiómetro',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00194','sanidad'),
('IB','dept-sanidad','','Fonendoscopio',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00195','sanidad'),
('IB','dept-actividadesfisicas','','Piragua de iniciación',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00196','actividadesfisicas'),
('IB','dept-actividadesfisicas','','Bicicleta estática',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00197','actividadesfisicas'),
('IB','dept-actividadesfisicas','','Material de escalada',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00198','actividadesfisicas'),
('IB','dept-administracion','','Ordenador de sobremesa',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00199','administracion'),
('IB','dept-administracion','','Escáner de documentos',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00200','administracion'),
('IB','dept-administracion','','Fotocopiadora',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00201','administracion'),
('IB','dept-comercio','','Terminal punto de venta',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00202','comercio'),
('IB','dept-comercio','','Caja registradora',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00203','comercio'),
('IB','dept-comercio','','Estantería de exposición',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00204','comercio'),
('IB','dept-edificacionobracivil','','Nivel láser',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00205','edificacionobracivil'),
('IB','dept-edificacionobracivil','','Maqueta estructural',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00206','edificacionobracivil'),
('IB','dept-edificacionobracivil','','Casco de obra',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00207','edificacionobracivil'),
('IB','dept-edificacionobracivil','','Cinta métrica de obra',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00208','edificacionobracivil'),
('IB','dept-electricidadelectronica','','Osciloscopio',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00209','electricidadelectronica'),
('IB','dept-electricidadelectronica','','Fuente de alimentación',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00210','electricidadelectronica'),
('IB','dept-electricidadelectronica','','Polímetro',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00211','electricidadelectronica'),
('IB','dept-electricidadelectronica','','Placa de prácticas',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00212','electricidadelectronica'),
('IB','dept-fabricacionmecanica','','Torno mecánico',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00213','fabricacionmecanica'),
('IB','dept-fabricacionmecanica','','Fresadora',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00214','fabricacionmecanica'),
('IB','dept-fabricacionmecanica','','Juego de calibres',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00215','fabricacionmecanica'),
('IB','dept-imagenpersonal','','Sillón de peluquería',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00216','imagenpersonal'),
('IB','dept-imagenpersonal','','Secador profesional',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00217','imagenpersonal'),
('IB','dept-imagenpersonal','','Maniquí de práctica',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00218','imagenpersonal'),
('IB','dept-informatica','','Servidor de prácticas',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00219','informatica'),
('IB','dept-informatica','','Switch de red',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00220','informatica'),
('IB','dept-informatica','','Router Cisco',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00221','informatica'),
('IB','dept-informatica','','Portátil de pruebas',1,1,'Material didáctico','Aula del departamento','Bueno','','IB-00222','informatica');
